name: ECI Linker

on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'

jobs:
  say-hi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a Hello world!
        run: echo 'Hello World from ECI Linker'

  install-dependencies:
    runs-on: ubuntu-latest
    uses: ./
        # the parameters below are only necessary
        # because we are running these examples in a monorepo
        with:
          working-directory: .
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          # build: npm install
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
