name: ECI Linker

on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a Hello world!
        run: echo 'Hello World from ECI Linker'

  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Lint code
        run: npm run lint
