name: ECI Linker

on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a Hello world!
        run: echo 'Hello World from ECI Linker'

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ../app
        run: npm install
      - name: Run tests
        uses: ../app
        run: npm run test
